Packaging run
Packaging was run, but R gave me the following feedback, so it propable did not work correct.

> build("phenologicalOverlap", path="phenologicalOverlap")   # build the .tar.gz file
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R"  \
  --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD  \
  build  \
  "C:\Users\Florian\Documents\GitHub\phenologicalOverlap"  \
  --no-resave-data --no-manual

* checking for file 'C:\Users\Florian\Documents\GitHub\phenologicalOverlap/DESCRIPTION' ... OK
* preparing 'phenologicalOverlap':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warnung: Ausführung von Kommando '"C:/PROGRA~1/R/R-34~1.2/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' ergab Status 1
 ERROR
Warnung: Ausführung von Kommando '"pdflatex" -halt-on-error -interaction=batchmode "phenologicalOverlap-vignetteknitr.tex"' ergab Status 127
Warnung: Ausführung von Kommando '"pdflatex" -halt-on-error -interaction=batchmode "phenologicalOverlap-vignetteknitr.tex"' ergab Status 127
Fehler: Verarbeitung der Vignette 'phenologicalOverlap-vignetteknitr.Rmd' mit folgender Diagnose fehlgeschlagen:
Failed to compile phenologicalOverlap-vignetteknitr.tex.
Ausführung angehalten
Error: Command failed (1)
> install("phenologicalOverlap") # install on the computer
Installing phenologicalOverlap
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R"  \
  --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/Florian/Documents/GitHub/phenologicalOverlap"  \
  --library="C:/Users/Florian/Documents/R/win-library/3.4"  \
  --install-tests

* installing *source* package 'phenologicalOverlap' ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (phenologicalOverlap)
Reloading installed phenologicalOverlap

Attaching package: ‘phenologicalOverlap’

The following objects are masked _by_ ‘.GlobalEnv’:

    BetaData, CheckData,
    CheckHurlbert, CheckProbData,
    checkProbFunc, CountsToDrawing,
    estdist, EstimatorData, FillUp,
    funcfromdata, kernelest,
    loglikelihood, normalize,
    NormData, NormDataDates,
    PackageCheck, sameXs, uniform,
    wmd